import Head from "next/head"
import Footer from "./footer"
import Navbar from "./navbar"

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        {/* <title>Encargo {title ? `| ${title}` : ""}</title> */}
        <title>Encargo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <div>{children}</div>

      <Footer />
    </div>
  )
}